### DISCUSSION TITLE
Allow LLVM compilers to be used on MacOS?

### DISCUSSION THREAD

**Discussion by natalie-perlin** [JCSDA/spack-stack#1373] [General]
Could LLVM compilers be allowed for building spack-stack on MacOS? Testing a build of spack-stack-1.8.0 on x86_64 Monterey.
It looks like only apple-clang compilers are accepted on Darwin platforms. Concretization fails in the very beginning, see below the errors.
I've installed llvm v19.1.3 with clang, clang++, prepared a modulefile that is loaded before building anything in stack. A file compiler.yaml was set as follows:

```
compilers:
- compiler:
    spec: clang@=19.1.3
    paths:
      cc: /usr/local/opt/llvm/bin/clang
      cxx: /usr/local/opt/llvm/bin/clang++
      f77: /usr/local/bin/gfortran-12
      fc: /usr/local/bin/gfortran-12
#    flags: {}
    flags:
      ldflags: -Wl,-ld_classic           # Add this ldflags spec
    operating_system: monterey
    target: x86_64
    modules:
    - llvm-clang/19.1.3
    environment:
      prepend_path:
        MODULEPATH: /Users/Natalie/spack-stack/modulefiles
    extra_rpaths: []
- compiler:
    spec: gcc@=12.4.0
    paths:
      cc: /usr/local/bin/gcc-12
      cxx: /usr/local/bin/g++-12
      f77: /usr/local/bin/gfortran-12
      fc: /usr/local/bin/gfortran-12
    flags: {}
    operating_system: monterey
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```
    
gcc in the environment points to the system Apple-clang 14.0.0:

```
[Natalie@Mac:~/spack-stack/spack-stack-1.8.0-llvm/envs/ue-clang]$ which gcc
/usr/bin/gcc
[Natalie@Mac:~/spack-stack/spack-stack-1.8.0-llvm/envs/ue-clang]$ gcc --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

The concretization error is as follows:

```
 spack concretize 2>&1 | tee log.concretize
==> Warning: invalid escape sequence '\('
==> Error: cannot bootstrap the "clingo" Python module from spec "clingo-bootstrap@spack+python %apple-clang target=x86_64" due to the following failures:
spack-install raised ConflictsInSpecError: Conflicts in concretized spec "clingo-bootstrap@spack%apple-clang@14.0.0~docs~ipo~optimized+python build_system=cmake build_type=Release generator=make arch=darwin-monterey-x86_64/g7w7poc"

    List of matching conflicts for spec:

    libiconv@=1.17%apple-clang@=14.0.0 build_system=autotools libs=shared,static arch=darwin-monterey-x86_64
        ^gmake@=4.4.1%apple-clang@=14.0.0~guile build_system=generic arch=darwin-monterey-x86_64

1. "arch=darwin-None-None" conflicts with "libiconv"

Run `spack --debug ...` for more detailed errors
[Natalie@Mac:~/spack-stack/spack-stack-1.8.0-llvm/envs/ue-clang]$ module list

Currently Loaded Modules:
  1) llvm-clang/19.1.3
```

How to configure the llvm-clang to be used in lieu of apple-clang? Do gcc and/or g++ need to be pointing to llvm-clang to avoid the issue?
