### ISSUE TITLE
Build error for ecmwf-atlas when using recent Intel compilers and a gcc@12 backend

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#1000]
**Describe the bug**
When compiling with Intel, we need to use C++-17 capable `gcc` compiler as backend in spack. This is done through the compiler config, for example for Discover:
```
- compiler:
    spec: intel@=2021.10.0
    paths:
      cc: /usr/local/intel/oneapi/2021/compiler/2023.2.1/linux/bin/intel64/icc
      cxx: /usr/local/intel/oneapi/2021/compiler/2023.2.1/linux/bin/intel64/icpc
      f77: /usr/local/intel/oneapi/2021/compiler/2023.2.1/linux/bin/intel64/ifort
      fc: /usr/local/intel/oneapi/2021/compiler/2023.2.1/linux/bin/intel64/ifort
    flags:
      cflags: -diag-disable=10441
      cxxflags: -diag-disable=10441
      fflags: -diag-disable=10448
    operating_system: sles15
    target: x86_64
    modules:
    - comp/intel/2023.2.1
    environment:
      prepend_path:
        PATH: '/usr/local/other/gcc/11.4.0/bin'
        CPATH: '/usr/local/other/gcc/11.4.0/include'
        LD_LIBRARY_PATH: '/usr/local/intel/oneapi/2021/compiler/2023.2.1/linux/compiler/lib/intel64_lin:/usr/local/other/gcc/11.4.0/lib64'
      #set:
      #  I_MPI_ROOT: '/usr/local/intel/oneapi/2021/mpi/2021.5.0'
    extra_rpaths: []
```

With `gcc@9:11`, this works. With `gcc@12`,this fails for `ecmwf-atlas`:
```
[  3%] Linking CXX executable ../../../bin/atlas-io-list
cd /discover/nobackup/projects/jcsda/s2127/dheinzel/spstmil/cache/build_stage/spack-stage-ecmwf-atlas-0.36.0-ygvahpmfl4h44pyocjubiteaz4uaavwm/spack-src/build/atlas_io/src/tools && /gpfsm/dulocal15/sles15/other/cmake/3.28.2/bin/cmake -E remove /discover/nobackup/projects/jcsda/s2127/dheinzel/spstmil/cache/build_stage/spack-stage-ecmwf-atlas-0.36.0-ygvahpmfl4h44pyocjubiteaz4uaavwm/spack-src/build/bin/atlas-io-list
cd /discover/nobackup/projects/jcsda/s2127/dheinzel/spstmil/cache/build_stage/spack-stage-ecmwf-atlas-0.36.0-ygvahpmfl4h44pyocjubiteaz4uaavwm/spack-src/build/atlas_io/src/tools && /gpfsm/dulocal15/sles15/other/cmake/3.28.2/bin/cmake -E cmake_link_script CMakeFiles/atlas-io-list.dir/link.txt --verbose=1
/discover/nobackup/projects/jcsda/s2127/dheinzel/spstmil/spack/lib/spack/env/intel/icpc -O2 -g -DNDEBUG -Wl,--disable-new-dtags "CMakeFiles/atlas-io-list.dir/atlas-io-list.cc.o" -o ../../../bin/atlas-io-list -Wl,-rpath,"/gpfsm/dnb55/projects/p01/s2127/dheinzel/spstmil/envs/unified-env-intel-2021.10.0/install/intel/2021.10.0/ecmwf-atlas-0.36.0-ygvahpm/lib:/gpfsm/dnb55/projects/p01/s2127/dheinzel/spstmil/envs/unified-env-intel-2021.10.0/install/inl/2021.10.0/ecmwf-atlas-0.36.0-ygvahpm/lib64:/gpfsm/dnb55/projects/p01/s2127 \/dheinzel/spstmil/envs/unified-env-intel-2021.10.0/install/intel/2021.10.0/bzip2-1.0.8-secsaw2/lib:/gpfsm/dnb55/projects/p01/s2127/dheinzel/spstmil/envs/unified-env-intel-2021.10.0/install/intel/2021.10.0/lz4-1.9.4-wk7dz7k/lib:/gpfsm/dnb55/projects/p01/s2127/dheinzel/spstmil/envs/unified-env-intel-2021.10.0/install/intel/2021.10.0/ncurses-6.4-h57iiko/lib:/gpfsm/dnb55/projects/p01/s2127/dheinzel/spstmil/envs/unified-env-intel-2021.10.0/install/intel/2021.10.0/openblas-0.3.24-3k3ad6m/lib:/gpfsm/dnb55/projects/p01/s2127/dheinzel/spstmil/envs/unified-env-intel-2021.10.0/install/intel/2021.10.0/fftw-3.3.10-jwoymye/lib:/gpfsm/dnb55/projects/p01/s2127/dheinzel/spstmil/envs/unified-env-intel-2021.10.0/install/intel/2021.10.0/python-3.10.13-xusbxob/lib:/gpfsm/dnb55/projects/p01/s2127/dheinzel/spstmil/envs/unified-env-intel-2021.10.0/install/intel/2021.10.0/expat-2.5.0-iemkw7p/lib:/gpfsm/dnb55/projects/p01/s2127/dheinzel/spstmil/envs/unified-env-intel-2021.10.0/install/intel/2021.10.0/libbsd-0.11.7-pwug2g3/lib:/gpfsm/dnb55/projects/p01/s2127/dheinzel/spstmil/envs/unified-env-intel-2021.10.0/install/intel/2021.10.0/libmd-1.0.4-57q2udg/lib:/gpfsm/dnb55/projects/p01/s2127/dheinzel/spstmil/envs/unified-env-intel-2021.10.0/install/intel/2021.10.0/gdbm-1.23-fqmqprp/lib:/gpfsm/dnb55/projects/p01/s2127/dheinzel/spstmil/envs/unified-env-intel-2021.10.0/install/intel/2021.10.0/readline-8.2-ca6xvfd/lib:/gpfsm/dnb55/projects/p01/s2127/dheinzel/spstmil/envs/unified-env-intel-2021.10.0/install/intel/2021.10.0/libffi-3.4.4-eirpkvv/lib:/gpfsm/dnb55/projects/p01/s2127/dheinzel/spstmil/envs/unified-env-intel-2021.10.0/install/intel/2021.10.0/libxcrypt-4.4.35-cazjnai/lib:/gpfsm/dnb55/projects/p01/s2127/dheinzel/spstmil/envs/unified-env-intel-2021.10.0/install/intel/2021.10.0/sqlite-3.43.2-44pzvun/lib:/gpfsm/dnb55/projects/p01/s2127/dheinzel/spstmil/envs/unified-env-intel-2021.10.0/install/intel/2021.10.0/zlib-1.2.13-dyrl52j/lib:/gpfsm/dnb55/projects/p01/s2127/dheinzel/spstmil/envs/unified-env-intel-2021.10.0/install/intel/2021.10.0/util-linux-uuid-2.38.1-2te4m7v/lib:/gpfsm/dnb55/projects/p01/s2127/dheinzel/spstmil/envs/unified-env-intel-2021.10.0/install/intel/2021.10.0/xz-5.4.1-r65qkio/lib:/gpfsm/dnb55/projects/p01/s2127/dheinzel/spstmil/envs/unified-env-intel-2021.10.0/install/intel/2021.10.0/qhull-2020.2-ouqsjqu/lib:/gpfsm/dnb55/projects/p01/s2127/dheinzel/spstmil/envs/unified-env-intel-2021.10.0/install/intel/2021.10.0/eckit-1.24.5-ciukrk2/lib64:/gpfsm/dnb55/projects/p01/s2127/dheinzel/spstmil/envs/unified-env-intel-2021.10.0/install/intel/2021.10.0/ectrans-1.2.0-r3j4al7/lib64:/gpfsm/dnb55/projects/p01/s2127/dheinzel/spstmil/envs/unified-env-intel-2021.10.0/install/intel/2021.10.0/fiat-1.2.0-pyeukly/lib64:/gpfsm/dnb55/projects/p01/s2127/dheinzel/spstmil/envs/unified-env-intel-2021.10.0/install/intel/2021.10.0/fckit-0.11.0-bjqhnu4/lib64:\$ORIGIN/../lib64:/discover/nobackup/projects/jcsda/s2127/dheinzel/spstmil/envs/unified-env-intel-2021.10.0/install/intel/2021.10.0/eckit-1.24.5-ciukrk2/lib64" ../../../lib/libatlas_io.so \
/discover/nobackup/projects/jcsda/s2127/dheinzel/spstmil/envs/unified-env-intel-2021.10.0/install/intel/2021.10.0/eckit-1.24.5-ciukrk2/lib64/libeckit_option.so /discover/nobackup/projects/jcsda/s2127/dheinzel/spstmil/envs/unified-env-intel-2021.10.0/install/intel/2021.10.0/eckit-1.24.5-ciukrk2/lib64/libeckit.so -lm /usr/lib64/librt.so -lpthread -ldl

ld: ../../../lib/libatlas_io.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_use_local_data()' make[2]: *** [atlas_io/src/tools/CMakeFiles/atlas-io-list.dir/build.make:106: bin/atlas-io-list] Error 1 make[2]: Leaving directory '/gpfsm/dnb55/projects/p01/s2127/dheinzel/spstmil/cache/build_stage/spack-stage-ecmwf-atlas-0.36.0-ygvahpmfl4h44pyocjubiteaz4uaavwm/spack-src/build' make[1]: *** [CMakeFiles/Makefile2:1858: atlas_io/src/tools/CMakeFiles/atlas-io-list.dir/all] Error 2 make[1]: Leaving directory '/gpfsm/dnb55/projects/p01/s2127/dheinzel/spstmil/cache/build_stage/spack-stage-ecmwf-atlas-0.36.0-ygvahpmfl4h44pyocjubiteaz4uaavwm/spack-src/build' make: *** [Makefile:169: all] Error 2
```

I tried different versions of `ecmwf-atlas` (0.35.1 and 0.36.0), as well as different versions of the Intel compiler (2021.5.0 and 2021.10.0).

Other packages that require `C++-17` standard build fine regardless of the gcc backend (e.g. `eckit`, `fckit`).

My first guess is that there is another dependency in `ecmwf-atlas` that isn't compiled with `C++-17` standard, i.e. that uses `C++-11` and that gets pulled in here. But maybe that assumption is incorrect/

**To Reproduce**
See above

**Expected behavior**
It builds with `gcc@12` as backend

**System:**
Any system with Intel compilers supported in spack-stack

**Additional context**
n/a
