### ISSUE TITLE
How to handle multiple variants of FMS?

### ISSUE THREAD

**Issue by mathomp4** [JCSDA/spack-stack#1139]
Something I just thought about. Currently in spack-stack in `configs/common/packages.yaml` there is:
```yaml
    fms:
      version: ['2023.04']
      variants: precision=32,64 +quad_precision +gfs_phys +openmp +pic constants=GFS build_type=Release +deprecated_io
```

But eventually if GEOS moves in here and we use FMS from spack, it would most likely be built as:
```
variants: precision=32,64 +quad_precision ~gfs_phys +openmp +pic constants=GEOS build_type=Release +deprecated_io
```
aka we don't use GFS Physics and we have a different set of constants.

Would it be perhaps a new entry in `modules.yaml` based off of...the constants: a la:
```yaml
      fms:
        suffixes:
          constants=GEOS: 'geos'
          constants=GFS: 'gfs'
```

🤷🏼 Not too sure, just thinking ahead.

(I suppose something similar for if yaml support is built in as well?)
