### ISSUE TITLE
Concretize step fails when building develop branches (as of 8/7/24) on Orion for GCC

### ISSUE THREAD

**Issue by srherbener** [JCSDA/spack-stack#1223]
**Describe the bug**

Following instructions for setting up an environment and building spack-stack on Orion, the concretize step fails with this error message:
```
orion-login-2[38] herbener$ spack concretize 2>&1 | tee log.concretize
==> Warning: cannot detect libc from gcc@=12.2.0. The compiler will not be used during concretization.
==> Error: concretization failed for the following reasons:

   1. Cannot set the required compiler: madis%gcc
```

Here are the instructions I followed:

1. Setting environment: https://spack-stack.readthedocs.io/en/latest/PreConfiguredSites.html#msu-orion

2. Building new environment (GCC): https://spack-stack.readthedocs.io/en/latest/PreConfiguredSites.html#create-local-environment

I was able to get concretize to work by changing the paths for gcc in the `site/compilers.yaml` file. Here are the changes I made:
```
- compiler:
    spec: gcc@12.2.0
    paths:
      #cc: /apps/spack-managed/gcc-11.3.1/gcc-12.2.0-7cu3qahzhsxpauy4jlnsbcqmlbkxbbbo/bin/gcc
      #cxx: /apps/spack-managed/gcc-11.3.1/gcc-12.2.0-7cu3qahzhsxpauy4jlnsbcqmlbkxbbbo/bin/g++
      #f77: /apps/spack-managed/gcc-11.3.1/gcc-12.2.0-7cu3qahzhsxpauy4jlnsbcqmlbkxbbbo/bin/gfortran
      #fc: /apps/spack-managed/gcc-11.3.1/gcc-12.2.0-7cu3qahzhsxpauy4jlnsbcqmlbkxbbbo/bin/gfortran
      cc: /work/noaa/epic/role-epic/spack-stack/orion/installs/gcc/12.2.0/bin/gcc
      cxx: /work/noaa/epic/role-epic/spack-stack/orion/installs/gcc/12.2.0/bin/g++
      f77: /work/noaa/epic/role-epic/spack-stack/orion/installs/gcc/12.2.0/bin/gfortran
      fc: /work/noaa/epic/role-epic/spack-stack/orion/installs/gcc/12.2.0/bin/gfortran
    flags: {}
    operating_system: rocky9
    target: x86_64
    modules:
    - gcc/12.2.0
    environment: {}
    extra_rpaths: []
```

I could be doing something wrong, and it would be great to learn about that and fix the documentation.

Or if this seems truly a bug to others, would the workaround I used above be a good way to address this issue?

**To Reproduce**

Follow instructions in the spack-stack ReadTheDocs for building a new environment on Orion using GCC.

**Expected behavior**

I can build GCC spack-stack without any intervention (ie the workaround I mentioned above)

**System:**
What system(s) are you running the code on?
Orion, GCC

**Additional context**
