### ISSUE TITLE
WGRIB2 build in spack-stack-1.9.0 is missing symbols and modules point to a non-existent static library

### ISSUE THREAD

**Issue by mark-a-potts** [JCSDA/spack-stack#1515]
**Describe the bug**
When building with intel compilers (classic or oneapi), wgrib2 version 3.5.0 is being built with shared libs only. The libwgrib2.so library is missing a number of symbols including "psfor" and "psforint" which are actually part of wgrib2 (they are present in the executable for wgrib2). The module file produced for wgrib2 also sets WGRIB2_LIB to point to a non-existent static library. 

**To Reproduce**
I found this bug while testing against a containerized version of spack-stack-1.9.0, but it is also present in the install on Hera here-
/contrib/spack-stack/spack-stack-1.9.0-release/envs/ue-oneapi-2024.2.1

**Expected behavior**
All the symbols should be included in the shared objects and the module file should point the correct path/library.

**System:**
I found this in my container and on Hera, but @rickgrubin has confirmed it is an issue on Hercules and Ursa as well.

**Additional context**
The wgrib2 executable seems to be okay, but there seems to have been some issue that got introduced with the change from static to shared libs. I was able to edit the wgrib2 package.py file to allow for static builds again, and that resulted in all the symbols being included. I am not sure if that is the best approach to use, however. 

It looks like the problem with the missing symbols is resolve when using head of develop for wgrib2. There was a commit at the end of November 2024 that fixed this issue.

**Comment by rickgrubin-noaa** [comment]
[wgrib2 module file settings](https://github.com/JCSDA/spack-stack/blob/release/1.9.0/configs/common/modules_lmod.yaml#L233
)

```
      wgrib2:
        environment:
          set:
            'WGRIB2_INC': '{prefix}/include'
            'WGRIB2_LIB': '{prefix}/lib/libwgrib2.a'
            'WGRIB2': '{prefix}/bin/wgrib2'
```
