### ISSUE TITLE
Change zlib-ng to zlib on ursa

### ISSUE THREAD

**Issue by rickgrubin-noaa** [JCSDA/spack-stack#1556]
**Issue**
Revert `zlib-ng` to `zlib` and build within spack (do not use system-supplied library).

**Configuration Changes**
`configs/sites/tier1/ursa/packages_gcc.yaml`

Remove:

```
zlib-ng:
  require:
  - '~shared'
```

`configs/sites/tier1/ursa/packages_oneapi.yaml`

Remove:

```
zlib-ng:
  require:
  - '~shared'
```

`configs/sites/tier1/ursa/packages.yaml`

Change:

```
packages:
  all:
  zlib-api:
    buildable: False
  zlib:
    buildable: False
    externals:
    - spec: zlib@1.2.11
      prefix: /usr

```

to:

```
packages:
  all:
     providers:
      zlib-api:: [zlib]
  zlib:
    require::
    - '@1.2.13'
```

**System:**
**ursa**
