### ISSUE TITLE
Install boost headers only

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#18]
At JCSDA we only use the boost headers. As of today, there is no option (variant) in spack for this, therefore I made the boost installation a headers-only one by turning off virtually everything:
```
    boost:
      version: [1.72.0]
      # Make this a boost-headers package by compiling basically nothing
      variants: ~atomic ~chrono ~date_time ~exception ~filesystem ~graph ~iostreams ~locale ~log ~math ~mpi ~numpy +pic ~program_options ~python ~random ~regex ~serialization ~signals ~test ~timer ~wave cxxstd=14 visibility=hidden
```
We need to check if there is a better way to do this. And/or use the module projections to rename the `boost` module to `boost-headers` to avoid any misconception.
