### ISSUE TITLE
Set cache/stage dir in config.yaml

### ISSUE THREAD

**Issue by kgerheiser** [JCSDA/spack-stack#26]
I think the Spack staging/cache directories should be set to reside within spack-stack by default with `${SPACK_STACK_DIR}/cache`. Mirrors and package sources are difficult to find because they are placed in some opaque temp directory.

```
  # The build stage can be purged with `spack clean --stage` and
  # `spack clean -a`, so it is important that the specified directory uniquely
  # identifies Spack staging to avoid accidentally wiping out non-Spack work.
  build_stage:
    ${SPACK_STACK_DIR}/cache/build_stage

  # Directory in which to run tests and store test results.
  # Tests will be stored in directories named by date/time and package
  # name/hash.
  test_stage: ${SPACK_STACK_DIR}/cache/test_stage

  # Cache directory for already downloaded source tarballs and archived
  # repositories. This can be purged with `spack clean --downloads`.
  source_cache: ${SPACK_STACK_DIR}/cache/source_cache


  # Cache directory for miscellaneous files, like the package index.
  # This can be purged with `spack clean --misc-cache`
  misc_cache: ${SPACK_STACK_DIR}/cache/misc_cache
```
