### ISSUE TITLE
Setting up compiler toolchains

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#46]
Many of the JEDI packages are written in C++ and require support for newer C++ standards (currently `c++-14`, soon hopefully `c++-17`). To compile these packages with the current jedi-stack on systems where the default `libstdc++` is too old, we set up toolchains as follows (e.g. cheyenne):
```
# C++-14 compliant compiler settings
# set / export these variables when building for Intel compiler(s)
if [[ "$JEDI_COMPILER" =~ .*"intel"* ]]; then
    export CXXFLAGS="-gxx-name=/glade/u/apps/ch/opt/gnu/9.1.0/bin/g++ -Wl,-rpath,/glade/u/apps/ch/opt/gnu/9.1.0/lib64"
    export LDFLAGS="-gxx-name=/glade/u/apps/ch/opt/gnu/9.1.0/bin/g++ -Wl,-rpath,/glade/u/apps/ch/opt/gnu/9.1.0/lib64"
fi
```
This works within the limited scope of jedi-stack, but within spack and as I we are adding more software, doing the same in the compiler config breaks a lot of packages. I think I found a way to configure this in spack so that it works for all packages (currently building):
```
  - compiler:
      spec: intel@2021.2.0
      paths:
        cc: /glade/u/apps/opt/intel/2021.2/compiler/latest/linux/bin/intel64/icc
        cxx: /glade/u/apps/opt/intel/2021.2/compiler/latest/linux/bin/intel64/icpc
        f77: /glade/u/apps/opt/intel/2021.2/compiler/latest/linux/bin/intel64/ifort
        fc: /glade/u/apps/opt/intel/2021.2/compiler/latest/linux/bin/intel64/ifort
      flags: {}
      operating_system: sles12
      target: x86_64
      modules:
      - intel/2021.2
      environment:
        prepend_path:
          LD_LIBRARY_PATH: '/glade/u/apps/opt/intel/2021.2/compiler/2021.2.0/linux/compiler/lib/intel64_lin:/glade/u/apps/ch/opt/gnu/10.1.0/lib64'
          CXXFLAGS: '-std=c++14 -gxx-name=/glade/u/apps/ch/opt/gnu/10.1.0/bin/g++ -Wl,-rpath,/glade/u/apps/ch/opt/gnu/10.1.0/lib64'
      extra_rpaths: []
```
Note 1. I don't think `-std=c++14` is required, but it's currently building with that. Will try again later without it.
Note 2. For the reason to have the additional `LD_LIBRARY_PATH` `/glade/u/apps/opt/intel/2021.2/compiler/2021.2.0/linux/compiler/lib/intel64_lin` see #28
Note 3. Right now I also have
```
        set:
          I_MPI_ROOT: '/glade/u/apps/opt/intel/2021.2/mpi/latest'
```
in there to avoid these nasty `I_MPI_SUBSTITUTE_INSTALL_DIR` errors in various places. This can hopefully be removed, because we don't want any MPI dependency in the compiler config!
