### ISSUE TITLE
Static NetCDF being built on Orion because linker doesn't support shared libraries

### ISSUE THREAD

**Issue by kgerheiser** [JCSDA/spack-stack#56]
I think we've seen this before, but I don't know why. When I attempt to build on Orion, NetCDF-Fortran fails because NetCDF-C is built statically.

When looking at the config.log for NetCDF it says `checking if libtool supports shared libraries... no`.

Same error as https://github.com/spack/spack/issues/29354

**Comment by kgerheiser** [comment]
@climbfuji I have found this is related to the `ldflags` in `compilers.yaml` where we add `-gxx-name=`. I didn't encounter this behavior until this flag was added. Then, I removed it, and lo and behold:

```
configure:12240: checking whether the /apps/intel-2021.2/intel-2021.2/mpi/2021.2.0/bin/mpicc linker (/work/noaa/stmp/gkyle/spack-stack/spack/lib/spack/e\
nv/ld -m elf_x86_64) supports shared libraries
configure:13499: result: yes
```

**Comment by kgerheiser** [comment]
Maybe `configure` uses `ld` directly. `-gxx-name=` isn't a valid option to `ld`, as opposed to using the compiler as the linker. I wonder if we can get by just using `-gxx-name=` for `cxxflags`. There's also the option of passing these flags directly to the libraries that need them.

**Comment by kgerheiser** [comment]
Some ideas: append/prepend the newer GCC to the PATH so that Intel picks it up from there instead of using ldflags.

**Comment by climbfuji** [comment]
> Some ideas: append/prepend the newer GCC to the PATH so that Intel picks it up from there instead of using ldflags.

Yes, just set PATH, LD_LIBRARY_PATH and maybe CPATH would be a way.

I suspected the gxx flags ... but great that you could confirm. Also, I do have an update for static netcdf-c builds ... Will create a PR to demonstrate this tonight.

**Comment by kgerheiser** [comment]
This worked for me on Orion. Don't know if `-gcc-name` is necessary, but I was able to compile everything.

```
- compiler:
    spec: intel@2021.2.0
    paths:
      cc: /apps/intel-2021.2/intel-2021.2/compiler/2021.2.0/linux/bin/intel64/icc
      cxx: /apps/intel-2021.2/intel-2021.2/compiler/2021.2.0/linux/bin/intel64/icpc
      f77: /apps/intel-2021.2/intel-2021.2/compiler/2021.2.0/linux/bin/intel64/ifort
      fc: /apps/intel-2021.2/intel-2021.2/compiler/2021.2.0/linux/bin/intel64/ifort
    flags:
      cflags: '-gcc-name=/apps/gcc-10.2.0/gcc-10.2.0/bin/gcc'
      cxxflags: '-gxx-name=/apps/gcc-10.2.0/gcc-10.2.0/bin/g++'
      fflags: '-gcc-name=/apps/gcc-10.2.0/gcc-10.2.0/bin/gcc'
    operating_system: centos7
    target: x86_64
    modules:
    - intel/2021.2
    environment:
      prepend_path:
        PATH: '/apps/gcc-10.2.0/gcc-10.2.0/bin'
        LD_LIBRARY_PATH: '/apps/gcc-10.2.0/gcc-10.2.0/contrib/lib/'
```
