### ISSUE TITLE
gcc@13 not yet supported

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#578]
**Is your feature request related to a problem? Please describe.**
People are now getting gcc@13 as defaults in macOS Homebrew. This compiler is problematic. Many packages don't build with them (see some of the conversations in spack-stack over the last few days), and even if the environment builds there are segmentation faults when running code (https://github.com/JCSDA-internal/fv3-bundle/issues/104 if you can access this page).

**Describe the solution you'd like**
Of course, in the long run we need to fix the build and runtime problems. But for now, we should implement a guard that prevents users from building with gcc@13 / gfortran@13.

**Additional context**
n/a

**Comment by svahl991** [comment]
Another good change would be to update the documentation in section `4.1.3` in https://spack-stack.readthedocs.io/en/1.3.1/NewSiteConfigs.html to warn people doing the `brew install gcc` command.

**Comment by svahl991** [comment]
Note that after I did `brew install gcc@12` I had to manually make symbolic links so that the `gfortran` command would be found.
```
ln -s /usr/local/bin/gfortran-12 /usr/local/bin/gfortran
ln -s /usr/local/bin/gcc-12 /usr/local/bin/gcc
```

**Comment by climbfuji** [comment]
I think brew has a feature for that

**Comment by mathomp4** [comment]
I wonder if it might be good to advise users to `spack config edit compilers` and edit the `f77` and `fc` to point to the numbered executable? A la:

```yaml
compilers:
- compiler:
    spec: apple-clang@14.0.3
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /Users/mathomp4/.homebrew/brew/bin/gfortran-12
      fc: /Users/mathomp4/.homebrew/brew/bin/gfortran-12
    flags: {}
    operating_system: ventura
    target: aarch64
    modules: []
    environment: {}
    extra_rpaths: []
```
after installing `gcc@12`?

It looks like spack is smart enough to use the numbered-compilers first if my `compilers.yaml` is anything to go by after a `spack compiler find` when it makes "all gcc" compilers.
