### ISSUE TITLE
Add MET/METplus Variables to modulefiles

### ISSUE THREAD

**Issue by EdwardSnyder-NOAA** [JCSDA/spack-stack#782]
**Is your feature request related to a problem? Please describe.**
[Recently](https://github.com/ufs-community/ufs-srweather-app/pull/826), the SRW App changed the way it runs the verification tests by loading the MET/METplus modules versus declaring MET/METplus paths in the experiment. Because of this change, a few MET/METplus variables need to be added to their lua files in order for these tests to run.

**Describe the solution you'd like**
To resolve this issue, we would need to add these missing variables to their lua files. Please see the code block below for the requested changes needed in `https://github.com/JCSDA/spack-stack/blob/release/1.4.1/configs/common/modules.yaml`
```
met:
  environment:
     set:
       'MET_INSTALL_DIR': '{prefix}'
       'MET_BASE': '{prefix}/share/met'
metplus:
  environment:
     set:
       'METPLUS_PATH': '{prefix}'
```

**Additional context**
The upcoming SRW App release will be using the spack-stack-1.4.1 and will support the MET/METplus tests. Meaning we would like to add these changes to the spack-stack-1.4.1, if possible. If not, we can manually add these variables. But regardless we would like to have these changes in the develop branch before the next spack-stack release.
