### ISSUE TITLE
Issue with creating meta modules with spack-stack 1.5.1 under Ubuntu/Docker

### ISSUE THREAD

**Issue by uturuncoglu** [JCSDA/spack-stack#945]
**Describe the bug**
I am trying to install spack-stack 1.5.1 to a Ubuntu box under Docker container. In this case, everything is fine and all packages are installed without any issue until last step to create meta modules using `spack stack setup-meta-modules` command.

**To Reproduce**
- create container `docker run --rm --platform linux/amd64 -e DISPLAY=host.docker.internal:0 --net host -it ubuntu:latest`
- cd /opt
- git clone https://github.com/oceanmodeling/ufs-coastal-app.git
- cd ufs-coastal-app
- ./build_deps.sh --compiler=gcc@11.4.0 --mpi=openmpi@4.1.6 --install-core-pkgs --install-lmod -v
This will take time and install all the dependency but gives error as it found as following. BTW, if I checked the module names in the `/opt/./ufs.local/modulefiles/module-index.yaml` file they looks like following

```
module_index:
  mr53zfa5eus3xfktfbsi3kz3npwme54j:
    path: /opt/ufs.local/modulefiles/Core/bacio/2.4.1-mr53zfa.lua
    use_name: bacio/2.4.1-mr53zfa
  xees72jfzsc473p4ofkqveftxet6sqig:
    path: /opt/ufs.local/modulefiles/openmpi/4.1.6-bazsoby/Core/base-env/1.0.0-xees72j.lua
    use_name: base-env/1.0.0-xees72j
  m6k2xnxfp6wm2lp42kzb2wxwx4j2uxyx:
    path: /opt/ufs.local/modulefiles/Core/bzip2/1.0.8-m6k2xnx.lua
    use_name: bzip2/1.0.8-m6k2xnx
```

and they have hash names at the end of the module use_name (this is correct in the container that I manually installed). Maybe this will be fixed when meta-modules are created but not sure. I also manually follow the steps previously and it was fine. I am not sure what is the issue in my script since it is following the same procedure.

The content of the `/opt/spack-stack/envs/ufs.local/site/compilers.yaml` is like following,

```
compilers:
- compiler:
    spec: gcc@=11.4.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```

**Expected behavior**
Having meta modules.

**System:**
Ubuntu, 22.04.3 LTS under Docker container

**Additional context**
```
==> Regenerating lmod module files
Configuring basic directory information ...
  ... script directory: /opt/spack-stack/spack/lib/jcsda-emc/spack-stack/stack
  ... base directory: /opt/spack-stack/spack/lib/jcsda-emc/spack-stack
  ... spack directory: /opt/spack-stack/spack
Configuring active spack environment ...
  ... environment directory: /opt/spack-stack/envs/ufs.local
Parsing spack environment main config ...
  ... install directory: /opt/ufs.local
Parsing spack environment modules config ...
  ... configured to use lmod modules
  ... module directory: /opt/ufs.local/modulefiles
Parsing spack environment package config ...
  ... list of possible compilers: '['gcc@11.4.0', 'gcc', 'intel', 'pgi', 'clang', 'xl', 'nag', 'fj', 'aocc']'
  ... list of possible mpi providers: '['openmpi@4.1.6', 'openmpi', 'mpich']'
['module-index.yaml', 'Core', 'openmpi']
==> Error: No matching compilers found
```

**Comment by climbfuji** [comment]
Did you set the config:packages:all entries as per documentation? Something like
```
spack config add "packages:all:providers:mpi:[openmpi@4.1.5]"
spack config add "packages:all:compiler:[apple-clang@13.1.6]"
```
matching your compiler and mpi versions?

What is the contents of `/opt/ufs.local`?

**Comment by uturuncoglu** [comment]
@climbfuji Thanks for your help. Yes, I run those commands. Is there any way to double check. I think they will appear in `spack.yaml`. In my case it is shown like following,


```
# spack-stack hash: 2605d04
# spack hash: cc9780cd0e
spack:
  concretizer:
    unify: when_possible

  config:
    install_tree:
      root: /opt/ufs.local
  modules:
    default:
      roots:
        lmod: /opt/ufs.local/modulefiles
        tcl: /opt/ufs.local/modulefiles
      lmod:
        core_compilers:
        - gcc@=11.4.0
  view: false
  include:
  - site
  - common

  specs:
  - ufs-weather-model-env~debug
  packages:
    all:
      compiler: [gcc@11.4.0]
      providers:
        mpi: [openmpi@4.1.6]
    fontconfig:
      variants: +pic
    pixman:
      variants: +pic
    cairo:
      variants: +pic
    libffi:
      version:
      - '3.3'
```

I have following folder under that directory,

```
/opt/ufs.local/
|-- bin
|   `-- sbang
|-- gcc
|   `-- 11.4.0
|       |-- bacio-2.4.1-mr53zfa
|       |-- base-env-1.0.0-xees72j
|       |-- bzip2-1.0.8-m6k2xnx
|       |-- c-blosc-1.21.5-lgx4mxz
|       |-- cmake-3.23.1-q3kdrhh
|       |-- cprnc-1.0.3-am4dxph
|       |-- crtm-2.4.0.1-bys5n5a
|       |-- crtm-fix-2.4.0.1_emc-jkzbfos
|       |-- curl-8.4.0-rc2ezxf
|       |-- esmf-8.5.0-wy2lwzd
|       |-- expat-2.5.0-u5kpbc7
|       |-- fargparse-1.5.0-2yqzcum
|       |-- fms-2023.04-svdnm6g
|       |-- g2-3.4.5-qz6kili
|       |-- g2tmpl-1.10.2-2xva3qy
|       |-- gdbm-1.23-3d2ady7
|       |-- gettext-0.21.1-lpiiike
|       |-- gftl-1.10.0-pnnpgob
|       |-- gftl-shared-1.6.1-dgb6plh
|       |-- hdf5-1.14.0-lieg5z2
|       |-- hwloc-2.9.1-wcizhtu
|       |-- ip-4.3.0-3fqud5x
|       |-- jasper-2.0.32-7ll3w4u
|       |-- krb5-1.20.1-2q4sthb
|       |-- libaec-1.0.6-skct4kl
|       |-- libbsd-0.11.7-322ozf2
|       |-- libedit-3.1-20210216-6cxsakf
|       |-- libevent-2.1.12-3mi7mi3
|       |-- libffi-3.3-mvlyxmt
|       |-- libiconv-1.17-nzwvzyn
|       |-- libjpeg-turbo-2.1.0-bpk6pnm
|       |-- libmd-1.0.4-hzluctu
|       |-- libpciaccess-0.17-xfzogxu
|       |-- libpng-1.6.37-jjsdac4
|       |-- libxcrypt-4.4.35-q2m4qty
|       |-- libxml2-2.10.3-53bweqq
|       |-- libyaml-0.2.5-ts62deh
|       |-- lz4-1.9.4-nbakpg2
|       |-- mapl-2.40.3-ohcno55
|       |-- nccmp-1.9.0.1-cqd6vsg
|       |-- ncurses-6.4-a7y7nnp
|       |-- netcdf-c-4.9.2-lur2xpz
|       |-- netcdf-fortran-4.6.1-7zxqoxd
|       |-- nghttp2-1.57.0-2ce7efn
|       |-- numactl-2.0.14-nrwhgn5
|       |-- openblas-0.3.24-q65ugam
|       |-- openmpi-4.1.6-bazsoby
|       |-- openssh-9.5p1-cj7uljl
|       |-- openssl-3.1.3-6lzewj3
|       |-- parallel-netcdf-1.12.2-dnpsayl
|       |-- parallelio-2.5.10-6jhkq73
|       |-- pkg-config-0.29.2-sa4pcl5
|       |-- pmix-5.0.1-vab4yhz
|       |-- py-bottleneck-1.3.7-vujp3lb
|       |-- py-cftime-1.0.3.4-u5ynnu6
|       |-- py-cython-0.29.36-mcygbos
|       |-- py-et-xmlfile-1.0.1-r5ciajp
|       |-- py-f90nml-1.4.3-onzcpnd
|       |-- py-jinja2-3.1.2-lztju66
|       |-- py-markupsafe-2.1.3-zvr5vyb
|       |-- py-netcdf4-1.5.8-s6f2jr6
|       |-- py-numexpr-2.8.4-7mnnn6m
|       |-- py-numpy-1.22.3-cno4omf
|       |-- py-openpyxl-3.1.2-linbxew
|       |-- py-pandas-1.5.3-sfxry7w
|       |-- py-pip-23.1.2-m6hoiay
|       |-- py-python-dateutil-2.8.2-ks25p6r
|       |-- py-pytz-2023.3-y7ddjqn
|       |-- py-pyxlsb-1.0.10-3edchs2
|       |-- py-pyyaml-6.0-5dvlfax
|       |-- py-setuptools-63.4.3-rdcklus
|       |-- py-six-1.16.0-5wokqhr
|       |-- py-xlrd-2.0.1-6siatx7
|       |-- py-xlsxwriter-3.1.7-wecdmvp
|       |-- py-xlwt-1.3.0-fsq2khq
|       |-- python-3.10.13-3hws57v
|       |-- readline-8.2-nnpkmvt
|       |-- scotch-7.0.4-anqn7jy
|       |-- snappy-1.1.10-uzqxr54
|       |-- sp-2.5.0-467dlxb
|       |-- sqlite-3.43.2-j66erd5
|       |-- ufs-pyenv-1.0.0-fo3e4py
|       |-- ufs-weather-model-env-1.0.0-mhkdutq
|       |-- util-linux-uuid-2.38.1-4pzbp2b
|       |-- w3emc-2.10.0-2ju7vr6
|       |-- xz-5.4.1-eeftbzz
|       |-- zlib-1.2.13-pjmzzzk
|       `-- zstd-1.5.2-lklbosf
`-- modulefiles
    |-- Core
    |   |-- bacio
    |   |-- bzip2
    |   |-- c-blosc
    |   |-- cmake
    |   |-- crtm-fix
    |   |-- curl
    |   |-- expat
    |   |-- fargparse
    |   |-- g2
    |   |-- g2tmpl
    |   |-- gdbm
    |   |-- gettext
    |   |-- gftl
    |   |-- gftl-shared
    |   |-- git
    |   |-- git-lfs
    |   |-- hwloc
    |   |-- ip
    |   |-- jasper
    |   |-- krb5
    |   |-- libaec
    |   |-- libbsd
    |   |-- libedit
    |   |-- libevent
    |   |-- libffi
    |   |-- libiconv
    |   |-- libjpeg-turbo
    |   |-- libmd
    |   |-- libpciaccess
    |   |-- libpng
    |   |-- libxcrypt
    |   |-- libxml2
    |   |-- libyaml
    |   |-- lz4
    |   |-- m4
    |   |-- ncurses
    |   |-- nghttp2
    |   |-- numactl
    |   |-- openblas
    |   |-- openmpi
    |   |-- openssh
    |   |-- openssl
    |   |-- perl
    |   |-- pkg-config
    |   |-- pmix
    |   |-- py-bottleneck
    |   |-- py-cftime
    |   |-- py-cython
    |   |-- py-et-xmlfile
    |   |-- py-f90nml
    |   |-- py-jinja2
    |   |-- py-markupsafe
    |   |-- py-numexpr
    |   |-- py-numpy
    |   |-- py-openpyxl
    |   |-- py-pandas
    |   |-- py-pip
    |   |-- py-python-dateutil
    |   |-- py-pytz
    |   |-- py-pyxlsb
    |   |-- py-pyyaml
    |   |-- py-setuptools
    |   |-- py-six
    |   |-- py-xlrd
    |   |-- py-xlsxwriter
    |   |-- py-xlwt
    |   |-- python
    |   |-- readline
    |   |-- snappy
    |   |-- sp
    |   |-- sqlite
    |   |-- tar
    |   |-- util-linux-uuid
    |   |-- w3emc
    |   |-- wget
    |   |-- xz
    |   |-- zlib
    |   `-- zstd
    |-- module-index.yaml
    `-- openmpi
        `-- 4.1.6-bazsoby
```
